language: go

go:
  - 1.x

sudo: false

install:
  - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -E "hugo_[^extended](.*)_Linux-64bit.deb" | cut -d ":" -f 2,3 | tr -d \" | grep https | wget -i - -O hugo.deb
  - sudo dpkg -i hugo.deb
  - npm install netlify-cli -g

script:
  - hugo

deploy:
  provider: script
  script: netlify deploy --dir=public --prod
  skip_cleanup: true
  on:
    branch: master
